import { Store } from '@/utils/Store'
import { useSession } from 'next-auth/react'
import Head from 'next/head'
import Link from 'next/link'
import React, { useContext, useEffect, useState } from 'react'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

const Layout = ({ title, children }) => {
  const { status, data: session } = useSession()
  const { state } = useContext(Store)
  const { cart } = state

  const [cartItemsCount, setCartItemsCount] = useState(0)

  useEffect(() => {
    setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0))
  }, [cart.cartItems])

  return (
    <>
      <Head>
        <title>{title ? title + ' BuyItNow' : "BuyItNow"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ToastContainer position='top-center' limit={1} />

      <div className='flex min-h-screen flex-col justify-between'>
        <header>
          <nav className='flex h-12 items-center px-4 justify-between shadow-md'>
            <Link className='text-lg font-bold' href="/">
              buyItnow
            </Link>
            <div>
              <Link className='p-2' href="/cart">
                {cartItemsCount > 0 && (
                  <span className='mt-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white'>
                    <a>{cartItemsCount}</a>
                  </span>
                )}
                Carrinho
              </Link>
              {status === 'loading' ?
                ('Loading') :
                session?.user ? (session.user.name) :
                  <Link className='p-2' href='/login'>
                    Login
                  </Link>
              }
            </div>
          </nav>
        </header>
        <main className='container m-auto mt-4 px-4'>
          {children}
        </main>
        <footer className='flex h-10 justify-center items-center shadow-inner'>
          <p className='text-sm font-light'>Copyright &copy; 2023 LS Software </p>
        </footer>
      </div>
    </>
  )
}

export default Layout