import { Store } from '@/utils/Store'
import { signOut, useSession } from 'next-auth/react'
import Head from 'next/head'
import Link from 'next/link'
import React, { useContext, useEffect, useState } from 'react'
import { ToastContainer } from 'react-toastify'
import { Menu } from '@headlessui/react'
import { UserIcon, ShoppingBagIcon, UserCircleIcon } from '@heroicons/react/outline'
import 'react-toastify/dist/ReactToastify.css'
import DropdownLink from './DropdownLink'
import Cookies from 'js-cookie'

const Layout = ({ title, children }) => {
  const { status, data: session } = useSession()
  const { state, dispatch } = useContext(Store)
  const { cart } = state

  const [cartItemsCount, setCartItemsCount] = useState(0)

  const logoutClickHandler = () => {
    Cookies.remove('cart')
    dispatch({ type: 'CART_RESET' })
    signOut({ callbackUrl: '/login' })
  }

  useEffect(() => {
    setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0))
  }, [cart.cartItems])

  return (
    <>
      <Head>
        <title>{title ? title + ' BuyItNow' : "BuyItNow"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ToastContainer position='top-center' limit={1} />

      <div className='flex min-h-screen flex-col justify-between'>
        <header>
          <nav className='flex h-12 items-center px-4 justify-between shadow-md'>
            <Link className='text-lg font-bold' href="/">
              BuyItNow
            </Link>
            <div>
              <Link className='p-2' href="/cart">
                {cartItemsCount > 0 && (
                  <span className='mt-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white'>
                    <a>{cartItemsCount}</a>
                  </span>
                )}
                Carrinho
              </Link>
              {status === 'loading' ?
                ('Loading') :
                <div>
                  {session?.user}
                </div>
                  ?
                  <Menu as={'div'} className="relative inline-block">
                    <Menu.Button className="flex flex-row align-middle text-green-600 hover:text-green-800 ml-4 mr-8 font-semibold">
                      {session.user.name}
                      <UserCircleIcon className='h-6 w-6 ml-2' />
                    </Menu.Button>
                    <Menu.Items className="absolute right-0 w-56 origin-top-right bg-white shadow-lg">
                      <Menu.Item>
                        <DropdownLink className='dropdown-link'>
                          Perfil
                        </DropdownLink>
                      </Menu.Item>
                      <Menu.Item>
                        <DropdownLink
                          className='dropdown-link'
                          href='/order-history'>
                          Histórico
                        </DropdownLink>
                      </Menu.Item>
                      <Menu.Item>
                        <DropdownLink
                          className='dropdown-link'
                          href='#'
                          onClick={logoutClickHandler}>
                          Sair
                        </DropdownLink>
                      </Menu.Item>
                    </Menu.Items>
                  </Menu> :
                  <Link className='p-2' href='/login'>
                    Login
                  </Link>
              }
            </div>
          </nav>
        </header>
        <main className='container m-auto mt-4 px-4'>
          {children}
        </main>
        <footer className='flex h-10 justify-center items-center shadow-inner'>
          <p className='text-sm font-light'>Copyright &copy; 2023 LS Software </p>
        </footer>
      </div>
    </>
  )
}

export default Layout